services:
  app:
    build:
      context: ./go
    tty: true
    stdin_open: true
    volumes:
      - ./go/:/go/src/app
    ports:
      - "8888:8080"
    container_name: hexagonal-architecture-backend
    environment:
      - PORT=8080
    depends_on:
      - db
  db:
    build:
      context: ./db
    restart: always
    ports:
      - "3333:3306"
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data:
    driver: local