services:
  app:
    build:
      context: ./go
    tty: true
    stdin_open: true
    volumes:
      - ./go/:/go/src/app
    ports:
      - "8888:8888"
    container_name: hexagonal-architecture-backend
    environment:
    - PORT=8888
