services:
  app_test:
    build:
      context: ./go
      dockerfile: ./docker/test/Dockerfile
    image: hexagonal-architecture-backend-test
    tty: true
    stdin_open: true
    volumes:
      - ./go/:/go/src/app
    ports:
      - "18888:8080"
    environment:
      - PORT=8080
    depends_on:
      - db_test
  db_test:
    build:
      context: ./db
      dockerfile: ./docker/test/Dockerfile
    image: hexagonal-architecture-backend-db-test
    restart: always
    ports:
      - "33333:3306"
    volumes:
      - db-data-test:/var/lib/mysql
volumes:
  db-data-test:
    driver: local