services:
  app:
    build:
      context: ./go
    tty: true
    stdin_open: true
    volumes:
      - ./go/:/go/src/app
    ports:
      - "8888:8080"
    environment:
      - PORT=8080
    depends_on:
      - db
    networks:
      - app_network
  db:
    build:
      context: ./db
    restart: always
    ports:
      - "3333:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app_network
  migration:
    build:
      context: ./migration
    volumes:
      - ./migration/:/go/src/migration
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network

volumes:
  db-data:
    driver: local
  nuxt_node_modules:

networks:
  app_network:
    driver: bridge