// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package schemas

var TableNames = struct {
	Comments         string
	Followers        string
	Posts            string
	SchemaMigrations string
	Tags             string
	ThreadTags       string
	Threads          string
	Users            string
	UsersComments    string
	UsersTags        string
}{
	Comments:         "comments",
	Followers:        "followers",
	Posts:            "posts",
	SchemaMigrations: "schema_migrations",
	Tags:             "tags",
	ThreadTags:       "thread_tags",
	Threads:          "threads",
	Users:            "users",
	UsersComments:    "users_comments",
	UsersTags:        "users_tags",
}
