// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package schemas

var TableNames = struct {
	Comments      string
	Followers     string
	Posts         string
	Tags          string
	ThreadTags    string
	Threads       string
	Users         string
	UsersComments string
	UsersTags     string
}{
	Comments:      "comments",
	Followers:     "followers",
	Posts:         "posts",
	Tags:          "tags",
	ThreadTags:    "thread_tags",
	Threads:       "threads",
	Users:         "users",
	UsersComments: "users_comments",
	UsersTags:     "users_tags",
}
