// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package schemas

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// Thread is an object representing the database table.
type Thread struct {
	ID        string      `boil:"id" json:"id" toml:"id" yaml:"id"`
	Title     string      `boil:"title" json:"title" toml:"title" yaml:"title"`
	UserID    null.String `boil:"user_id" json:"user_id,omitempty" toml:"user_id" yaml:"user_id,omitempty"`
	CreatedAt null.Time   `boil:"created_at" json:"created_at,omitempty" toml:"created_at" yaml:"created_at,omitempty"`

	R *threadR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L threadL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var ThreadColumns = struct {
	ID        string
	Title     string
	UserID    string
	CreatedAt string
}{
	ID:        "id",
	Title:     "title",
	UserID:    "user_id",
	CreatedAt: "created_at",
}

var ThreadTableColumns = struct {
	ID        string
	Title     string
	UserID    string
	CreatedAt string
}{
	ID:        "threads.id",
	Title:     "threads.title",
	UserID:    "threads.user_id",
	CreatedAt: "threads.created_at",
}

// Generated where

var ThreadWhere = struct {
	ID        whereHelperstring
	Title     whereHelperstring
	UserID    whereHelpernull_String
	CreatedAt whereHelpernull_Time
}{
	ID:        whereHelperstring{field: "`threads`.`id`"},
	Title:     whereHelperstring{field: "`threads`.`title`"},
	UserID:    whereHelpernull_String{field: "`threads`.`user_id`"},
	CreatedAt: whereHelpernull_Time{field: "`threads`.`created_at`"},
}

// ThreadRels is where relationship names are stored.
var ThreadRels = struct {
	User       string
	Posts      string
	ThreadTags string
}{
	User:       "User",
	Posts:      "Posts",
	ThreadTags: "ThreadTags",
}

// threadR is where relationships are stored.
type threadR struct {
	User       *User          `boil:"User" json:"User" toml:"User" yaml:"User"`
	Posts      PostSlice      `boil:"Posts" json:"Posts" toml:"Posts" yaml:"Posts"`
	ThreadTags ThreadTagSlice `boil:"ThreadTags" json:"ThreadTags" toml:"ThreadTags" yaml:"ThreadTags"`
}

// NewStruct creates a new relationship struct
func (*threadR) NewStruct() *threadR {
	return &threadR{}
}

func (r *threadR) GetUser() *User {
	if r == nil {
		return nil
	}
	return r.User
}

func (r *threadR) GetPosts() PostSlice {
	if r == nil {
		return nil
	}
	return r.Posts
}

func (r *threadR) GetThreadTags() ThreadTagSlice {
	if r == nil {
		return nil
	}
	return r.ThreadTags
}

// threadL is where Load methods for each relationship are stored.
type threadL struct{}

var (
	threadAllColumns            = []string{"id", "title", "user_id", "created_at"}
	threadColumnsWithoutDefault = []string{"id", "title", "user_id"}
	threadColumnsWithDefault    = []string{"created_at"}
	threadPrimaryKeyColumns     = []string{"id"}
	threadGeneratedColumns      = []string{}
)

type (
	// ThreadSlice is an alias for a slice of pointers to Thread.
	// This should almost always be used instead of []Thread.
	ThreadSlice []*Thread
	// ThreadHook is the signature for custom Thread hook methods
	ThreadHook func(context.Context, boil.ContextExecutor, *Thread) error

	threadQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	threadType                 = reflect.TypeOf(&Thread{})
	threadMapping              = queries.MakeStructMapping(threadType)
	threadPrimaryKeyMapping, _ = queries.BindMapping(threadType, threadMapping, threadPrimaryKeyColumns)
	threadInsertCacheMut       sync.RWMutex
	threadInsertCache          = make(map[string]insertCache)
	threadUpdateCacheMut       sync.RWMutex
	threadUpdateCache          = make(map[string]updateCache)
	threadUpsertCacheMut       sync.RWMutex
	threadUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var threadAfterSelectMu sync.Mutex
var threadAfterSelectHooks []ThreadHook

var threadBeforeInsertMu sync.Mutex
var threadBeforeInsertHooks []ThreadHook
var threadAfterInsertMu sync.Mutex
var threadAfterInsertHooks []ThreadHook

var threadBeforeUpdateMu sync.Mutex
var threadBeforeUpdateHooks []ThreadHook
var threadAfterUpdateMu sync.Mutex
var threadAfterUpdateHooks []ThreadHook

var threadBeforeDeleteMu sync.Mutex
var threadBeforeDeleteHooks []ThreadHook
var threadAfterDeleteMu sync.Mutex
var threadAfterDeleteHooks []ThreadHook

var threadBeforeUpsertMu sync.Mutex
var threadBeforeUpsertHooks []ThreadHook
var threadAfterUpsertMu sync.Mutex
var threadAfterUpsertHooks []ThreadHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Thread) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range threadAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Thread) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range threadBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Thread) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range threadAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Thread) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range threadBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Thread) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range threadAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Thread) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range threadBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Thread) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range threadAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Thread) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range threadBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Thread) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range threadAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddThreadHook registers your hook function for all future operations.
func AddThreadHook(hookPoint boil.HookPoint, threadHook ThreadHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		threadAfterSelectMu.Lock()
		threadAfterSelectHooks = append(threadAfterSelectHooks, threadHook)
		threadAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		threadBeforeInsertMu.Lock()
		threadBeforeInsertHooks = append(threadBeforeInsertHooks, threadHook)
		threadBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		threadAfterInsertMu.Lock()
		threadAfterInsertHooks = append(threadAfterInsertHooks, threadHook)
		threadAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		threadBeforeUpdateMu.Lock()
		threadBeforeUpdateHooks = append(threadBeforeUpdateHooks, threadHook)
		threadBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		threadAfterUpdateMu.Lock()
		threadAfterUpdateHooks = append(threadAfterUpdateHooks, threadHook)
		threadAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		threadBeforeDeleteMu.Lock()
		threadBeforeDeleteHooks = append(threadBeforeDeleteHooks, threadHook)
		threadBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		threadAfterDeleteMu.Lock()
		threadAfterDeleteHooks = append(threadAfterDeleteHooks, threadHook)
		threadAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		threadBeforeUpsertMu.Lock()
		threadBeforeUpsertHooks = append(threadBeforeUpsertHooks, threadHook)
		threadBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		threadAfterUpsertMu.Lock()
		threadAfterUpsertHooks = append(threadAfterUpsertHooks, threadHook)
		threadAfterUpsertMu.Unlock()
	}
}

// One returns a single thread record from the query.
func (q threadQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Thread, error) {
	o := &Thread{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "schemas: failed to execute a one query for threads")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all Thread records from the query.
func (q threadQuery) All(ctx context.Context, exec boil.ContextExecutor) (ThreadSlice, error) {
	var o []*Thread

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "schemas: failed to assign all query results to Thread slice")
	}

	if len(threadAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all Thread records in the query.
func (q threadQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "schemas: failed to count threads rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q threadQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "schemas: failed to check if threads exists")
	}

	return count > 0, nil
}

// User pointed to by the foreign key.
func (o *Thread) User(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("`id` = ?", o.UserID),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// Posts retrieves all the post's Posts with an executor.
func (o *Thread) Posts(mods ...qm.QueryMod) postQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("`posts`.`thread_id`=?", o.ID),
	)

	return Posts(queryMods...)
}

// ThreadTags retrieves all the thread_tag's ThreadTags with an executor.
func (o *Thread) ThreadTags(mods ...qm.QueryMod) threadTagQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("`thread_tags`.`thread_id`=?", o.ID),
	)

	return ThreadTags(queryMods...)
}

// LoadUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (threadL) LoadUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybeThread interface{}, mods queries.Applicator) error {
	var slice []*Thread
	var object *Thread

	if singular {
		var ok bool
		object, ok = maybeThread.(*Thread)
		if !ok {
			object = new(Thread)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeThread)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeThread))
			}
		}
	} else {
		s, ok := maybeThread.(*[]*Thread)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeThread)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeThread))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &threadR{}
		}
		if !queries.IsNil(object.UserID) {
			args[object.UserID] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &threadR{}
			}

			if !queries.IsNil(obj.UserID) {
				args[obj.UserID] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(userAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.User = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.Threads = append(foreign.R.Threads, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.UserID, foreign.ID) {
				local.R.User = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.Threads = append(foreign.R.Threads, local)
				break
			}
		}
	}

	return nil
}

// LoadPosts allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (threadL) LoadPosts(ctx context.Context, e boil.ContextExecutor, singular bool, maybeThread interface{}, mods queries.Applicator) error {
	var slice []*Thread
	var object *Thread

	if singular {
		var ok bool
		object, ok = maybeThread.(*Thread)
		if !ok {
			object = new(Thread)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeThread)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeThread))
			}
		}
	} else {
		s, ok := maybeThread.(*[]*Thread)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeThread)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeThread))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &threadR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &threadR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`posts`),
		qm.WhereIn(`posts.thread_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load posts")
	}

	var resultSlice []*Post
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice posts")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on posts")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for posts")
	}

	if len(postAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.Posts = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &postR{}
			}
			foreign.R.Thread = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if queries.Equal(local.ID, foreign.ThreadID) {
				local.R.Posts = append(local.R.Posts, foreign)
				if foreign.R == nil {
					foreign.R = &postR{}
				}
				foreign.R.Thread = local
				break
			}
		}
	}

	return nil
}

// LoadThreadTags allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (threadL) LoadThreadTags(ctx context.Context, e boil.ContextExecutor, singular bool, maybeThread interface{}, mods queries.Applicator) error {
	var slice []*Thread
	var object *Thread

	if singular {
		var ok bool
		object, ok = maybeThread.(*Thread)
		if !ok {
			object = new(Thread)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeThread)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeThread))
			}
		}
	} else {
		s, ok := maybeThread.(*[]*Thread)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeThread)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeThread))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &threadR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &threadR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`thread_tags`),
		qm.WhereIn(`thread_tags.thread_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load thread_tags")
	}

	var resultSlice []*ThreadTag
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice thread_tags")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on thread_tags")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for thread_tags")
	}

	if len(threadTagAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.ThreadTags = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &threadTagR{}
			}
			foreign.R.Thread = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.ThreadID {
				local.R.ThreadTags = append(local.R.ThreadTags, foreign)
				if foreign.R == nil {
					foreign.R = &threadTagR{}
				}
				foreign.R.Thread = local
				break
			}
		}
	}

	return nil
}

// SetUser of the thread to the related item.
// Sets o.R.User to related.
// Adds o to related.R.Threads.
func (o *Thread) SetUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `threads` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"user_id"}),
		strmangle.WhereClause("`", "`", 0, threadPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.UserID, related.ID)
	if o.R == nil {
		o.R = &threadR{
			User: related,
		}
	} else {
		o.R.User = related
	}

	if related.R == nil {
		related.R = &userR{
			Threads: ThreadSlice{o},
		}
	} else {
		related.R.Threads = append(related.R.Threads, o)
	}

	return nil
}

// RemoveUser relationship.
// Sets o.R.User to nil.
// Removes o from all passed in related items' relationships struct.
func (o *Thread) RemoveUser(ctx context.Context, exec boil.ContextExecutor, related *User) error {
	var err error

	queries.SetScanner(&o.UserID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("user_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.User = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.Threads {
		if queries.Equal(o.UserID, ri.UserID) {
			continue
		}

		ln := len(related.R.Threads)
		if ln > 1 && i < ln-1 {
			related.R.Threads[i] = related.R.Threads[ln-1]
		}
		related.R.Threads = related.R.Threads[:ln-1]
		break
	}
	return nil
}

// AddPosts adds the given related objects to the existing relationships
// of the thread, optionally inserting them as new records.
// Appends related to o.R.Posts.
// Sets related.R.Thread appropriately.
func (o *Thread) AddPosts(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Post) error {
	var err error
	for _, rel := range related {
		if insert {
			queries.Assign(&rel.ThreadID, o.ID)
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE `posts` SET %s WHERE %s",
				strmangle.SetParamNames("`", "`", 0, []string{"thread_id"}),
				strmangle.WhereClause("`", "`", 0, postPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			queries.Assign(&rel.ThreadID, o.ID)
		}
	}

	if o.R == nil {
		o.R = &threadR{
			Posts: related,
		}
	} else {
		o.R.Posts = append(o.R.Posts, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &postR{
				Thread: o,
			}
		} else {
			rel.R.Thread = o
		}
	}
	return nil
}

// SetPosts removes all previously related items of the
// thread replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.Thread's Posts accordingly.
// Replaces o.R.Posts with related.
// Sets related.R.Thread's Posts accordingly.
func (o *Thread) SetPosts(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Post) error {
	query := "update `posts` set `thread_id` = null where `thread_id` = ?"
	values := []interface{}{o.ID}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.Posts {
			queries.SetScanner(&rel.ThreadID, nil)
			if rel.R == nil {
				continue
			}

			rel.R.Thread = nil
		}
		o.R.Posts = nil
	}

	return o.AddPosts(ctx, exec, insert, related...)
}

// RemovePosts relationships from objects passed in.
// Removes related items from R.Posts (uses pointer comparison, removal does not keep order)
// Sets related.R.Thread.
func (o *Thread) RemovePosts(ctx context.Context, exec boil.ContextExecutor, related ...*Post) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	for _, rel := range related {
		queries.SetScanner(&rel.ThreadID, nil)
		if rel.R != nil {
			rel.R.Thread = nil
		}
		if _, err = rel.Update(ctx, exec, boil.Whitelist("thread_id")); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.Posts {
			if rel != ri {
				continue
			}

			ln := len(o.R.Posts)
			if ln > 1 && i < ln-1 {
				o.R.Posts[i] = o.R.Posts[ln-1]
			}
			o.R.Posts = o.R.Posts[:ln-1]
			break
		}
	}

	return nil
}

// AddThreadTags adds the given related objects to the existing relationships
// of the thread, optionally inserting them as new records.
// Appends related to o.R.ThreadTags.
// Sets related.R.Thread appropriately.
func (o *Thread) AddThreadTags(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*ThreadTag) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.ThreadID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE `thread_tags` SET %s WHERE %s",
				strmangle.SetParamNames("`", "`", 0, []string{"thread_id"}),
				strmangle.WhereClause("`", "`", 0, threadTagPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ThreadID, rel.TagID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.ThreadID = o.ID
		}
	}

	if o.R == nil {
		o.R = &threadR{
			ThreadTags: related,
		}
	} else {
		o.R.ThreadTags = append(o.R.ThreadTags, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &threadTagR{
				Thread: o,
			}
		} else {
			rel.R.Thread = o
		}
	}
	return nil
}

// Threads retrieves all the records using an executor.
func Threads(mods ...qm.QueryMod) threadQuery {
	mods = append(mods, qm.From("`threads`"))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"`threads`.*"})
	}

	return threadQuery{q}
}

// FindThread retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindThread(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*Thread, error) {
	threadObj := &Thread{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `threads` where `id`=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, threadObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "schemas: unable to select from threads")
	}

	if err = threadObj.doAfterSelectHooks(ctx, exec); err != nil {
		return threadObj, err
	}

	return threadObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Thread) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("schemas: no threads provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(threadColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	threadInsertCacheMut.RLock()
	cache, cached := threadInsertCache[key]
	threadInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			threadAllColumns,
			threadColumnsWithDefault,
			threadColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(threadType, threadMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(threadType, threadMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `threads` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `threads` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `threads` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, threadPrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	_, err = exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "schemas: unable to insert into threads")
	}

	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, identifierCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "schemas: unable to populate default values for threads")
	}

CacheNoHooks:
	if !cached {
		threadInsertCacheMut.Lock()
		threadInsertCache[key] = cache
		threadInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the Thread.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Thread) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	threadUpdateCacheMut.RLock()
	cache, cached := threadUpdateCache[key]
	threadUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			threadAllColumns,
			threadPrimaryKeyColumns,
		)
		if len(wl) == 0 {
			return 0, errors.New("schemas: unable to update threads, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `threads` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, threadPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(threadType, threadMapping, append(wl, threadPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "schemas: unable to update threads row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "schemas: failed to get rows affected by update for threads")
	}

	if !cached {
		threadUpdateCacheMut.Lock()
		threadUpdateCache[key] = cache
		threadUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q threadQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "schemas: unable to update all for threads")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "schemas: unable to retrieve rows affected for threads")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ThreadSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("schemas: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), threadPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `threads` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, threadPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "schemas: unable to update all in thread slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "schemas: unable to retrieve rows affected all in update all thread")
	}
	return rowsAff, nil
}

var mySQLThreadUniqueColumns = []string{
	"id",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Thread) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("schemas: no threads provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(threadColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLThreadUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	threadUpsertCacheMut.RLock()
	cache, cached := threadUpsertCache[key]
	threadUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			threadAllColumns,
			threadColumnsWithDefault,
			threadColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			threadAllColumns,
			threadPrimaryKeyColumns,
		)

		if !updateColumns.IsNone() && len(update) == 0 {
			return errors.New("schemas: unable to upsert threads, could not build update column list")
		}

		ret := strmangle.SetComplement(threadAllColumns, strmangle.SetIntersect(insert, update))

		cache.query = buildUpsertQueryMySQL(dialect, "`threads`", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `threads` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(threadType, threadMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(threadType, threadMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	_, err = exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "schemas: unable to upsert for threads")
	}

	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(threadType, threadMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "schemas: unable to retrieve unique values for threads")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, nzUniqueCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "schemas: unable to populate default values for threads")
	}

CacheNoHooks:
	if !cached {
		threadUpsertCacheMut.Lock()
		threadUpsertCache[key] = cache
		threadUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single Thread record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Thread) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("schemas: no Thread provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), threadPrimaryKeyMapping)
	sql := "DELETE FROM `threads` WHERE `id`=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "schemas: unable to delete from threads")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "schemas: failed to get rows affected by delete for threads")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q threadQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("schemas: no threadQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "schemas: unable to delete all from threads")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "schemas: failed to get rows affected by deleteall for threads")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ThreadSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(threadBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), threadPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `threads` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, threadPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "schemas: unable to delete all from thread slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "schemas: failed to get rows affected by deleteall for threads")
	}

	if len(threadAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Thread) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindThread(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ThreadSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := ThreadSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), threadPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `threads`.* FROM `threads` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, threadPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "schemas: unable to reload all in ThreadSlice")
	}

	*o = slice

	return nil
}

// ThreadExists checks if the Thread row exists.
func ThreadExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `threads` where `id`=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "schemas: unable to check if threads exists")
	}

	return exists, nil
}

// Exists checks if the Thread row exists.
func (o *Thread) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return ThreadExists(ctx, exec, o.ID)
}
