- id: "550e8400-e29b-41d4-a716-446655440000"
  username: "user1"
  email: "user1@example.com"
  password_hash: "$2a$10$NZSWLhO7eP5WZwfQ9k0KmeO6RMXDVdmPTVAidIJLh.W1HW9BX8kJa"
  created_at: "2023-04-01 10:00:00"

- id: "6ba7b810-9dad-11d1-80b4-00c04fd430c8"
  username: "user2"
  email: "user2@example.com"
  password_hash: "$2a$10$NZSWLhO7eP5WZwfQ9k0KmeO6RMXDVdmPTVAidIJLh.W1HW9BX8kJa"
  created_at: "2023-04-02 11:00:00"

- id: "6ba7b811-9dad-11d1-80b4-00c04fd430c8"
  username: "user3"
  email: "user3@example.com"
  password_hash: "$2a$10$NZSWLhO7eP5WZwfQ9k0KmeO6RMXDVdmPTVAidIJLh.W1HW9BX8kJa"
  created_at: "2023-04-03 12:00:00"

- id: "6ba7b812-9dad-11d1-80b4-00c04fd430c8"
  username: "user4"
  email: "user4@example.com"
  password_hash: "$2a$10$NZSWLhO7eP5WZwfQ9k0KmeO6RMXDVdmPTVAidIJLh.W1HW9BX8kJa"
  created_at: "2023-04-04 13:00:00"

- id: "6ba7b813-9dad-11d1-80b4-00c04fd430c8"
  username: "user5"
  email: "user5@example.com"
  password_hash: "$2a$10$NZSWLhO7eP5WZwfQ9k0KmeO6RMXDVdmPTVAidIJLh.W1HW9BX8kJa"
  created_at: "2023-04-05 14:00:00"