FROM mysql/mysql-server:8.0

ENV LANG=ja_JP.UTF-8
ENV MYSQL_USER=user
ENV MYSQL_PASSWORD=password
ENV MYSQL_DATABASE=hexagonal_architecture_backend_test
ENV MYSQL_ROOT_USER=root
ENV MYSQL_ROOT_PASSWORD=rootpassword
ENV MYSQL_ROOT_HOST=%
ENV TZ=Asia/Tokyo